name: Playwright Tests
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run test:ui-hotel
        env:
          CI: true
          TA_EMAIL: dummy
          TA_PASSWORD: dummy
          SLACK_BOT_TOKEN: dummy
          DWS_URL: dummy
          DWS_EMAIL: dummy
          DWS_PASSWORD: dummy
          REPORTS_PATH: dummy
          JIRA_BASE_URL: dummy
          JIRA_API_TOKEN: dummy
          JIRA_EMAIL: dummy
          JIRA_PROJECT: dummy

      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Deploy Playwright Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          destination_dir: reports/${{ github.run_id }} # Stores each run in a separate folder

      - name: Add Report Link to Workflow Summary
        if: always()
        run: |
          echo "### 📊 Playwright Report" >> $GITHUB_STEP_SUMMARY
          echo "View the live report here: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/reports/${{ github.run_id }}/" >> $GITHUB_STEP_SUMMARY
